input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["orders.enriched", "payments", "shipments"]
    codec => "json"
    decorate_events => true
    consumer_threads => 2
    group_id => "logstash-ecommerce"
    auto_offset_reset => "earliest"
  }
}

filter {
  if [kafka][topic] == "payments" {
    mutate {
      add_field => { "[@metadata][target_index]" => "ecommerce-payments" }
      add_field => { "event_type" => "payment" }
    }
  } else if [kafka][topic] == "orders.enriched" {
    mutate {
      add_field => { "[@metadata][target_index]" => "ecommerce-orders-enriched" }
      add_field => { "event_type" => "order_enriched" }
    }
  } else if [kafka][topic] == "shipments" {
    mutate {
      add_field => { "[@metadata][target_index]" => "ecommerce-shipments" }
      add_field => { "event_type" => "shipment" }
    }
  } else {
    mutate {
      add_field => { "[@metadata][target_index]" => "ecommerce-unknown" }
    }
  }

  if ![@timestamp] {
    ruby {
      code => "event.set('@timestamp', LogStash::Timestamp.now())"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    data_stream => false
    index => "%{[@metadata][target_index]}-%{+YYYY.MM.dd}"
    manage_template => false
  }
}
